services:
  mangaservice:
    image: mangaservice
    build:
      context: .
      dockerfile: MangaService/Dockerfile
    ports:
      - "0.0.0.0:5001:8080"

  notification:
    image: notification
    build:
      context: .
      dockerfile: Notification/Dockerfile
    ports:
      - "0.0.0.0:5002:8080"

  chapterservice:
    image: chapterservice
    build:
      context: .
      dockerfile: ChapterService/Dockerfile
    ports:
      - "0.0.0.0:5003:8080"

  userservice:
    image: userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile
    ports:
      - "0.0.0.0:5004:8080"

  categoryservice:
    image: categoryservice
    build:
      context: .
      dockerfile: CategoryService/Dockerfile
    ports:
      - "0.0.0.0:5005:8080"

  comment:
    image: comment
    build:
      context: .
      dockerfile: Comment/Dockerfile
    ports:
      - "0.0.0.0:5006:8080"
  
  frontend.client:
    image: frontend
    build:
      context: .
      dockerfile: FrontEnd/Dockerfile
    ports:
      - "0.0.0.0:4200:80"

networks:
  default:
    driver: bridge